### ISSUE TITLE
HTML : `data-url` should have priority on `href` attribute

### ISSUE THREAD

**Issue by ChipsVII** [SeptimusVII/framway-component-modalFW#1]
Consider the following HTML code : 

```html
<a href="my-href.html" data-url="my-href.html?modal=1" data-modal="my-modal">My link</a>
```

Expected behaviour :
- Clicking on the link will open a modal loading the URL `my-href.html?modal=1`
- `Right-click > Open in a new tab` will open `my-href.html`

Current behaviour :
- Clicking on the link will open a modal loading the URL `my-href.html`
- `Right-click > Open in a new tab` will open `my-href.html`

The solution would be to invert the test of attributes `href` & `data-url` in the `ModalFW.createModalFromTrigger`.

**Comment by SeptimusVII** [comment]
agreed and done in latest commit (`ac823af3b5b098355011e8a5f5827cba35444c78`)
